{% set version = '0.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-text2vec
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/text2vec_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/text2vec/text2vec_{{ version }}.tar.gz
  sha256: 5e8471ea68ee9d5f0d46c4a6f197af78dd160e8bb0246dcc0ff58b7ece66e564

build:
  merge_build_host: True  # [win]
  number: 1
  skip: True  # [r_base == "3.5.1"]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix >=1.1
    - r-r6 >=2.3.0
    - r-rcpp >=1.0.3
    - r-data.table >=1.9.6
    - r-digest >=0.6.8
    - r-lgr >=0.2
    - r-mlapi >=0.1.0
    - r-rsparse >=0.3.3.4
    - r-stringi >=1.1.5
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix >=1.1
    - r-r6 >=2.3.0
    - r-rcpp >=1.0.3
    - r-data.table >=1.9.6
    - r-digest >=0.6.8
    - r-lgr >=0.2
    - r-mlapi >=0.1.0
    - r-rsparse >=0.3.3.4
    - r-stringi >=1.1.5

test:
  commands:
    - $R -e "library('text2vec')"           # [not win]
    - "\"%R%\" -e \"library('text2vec')\""  # [win]

about:
  home: http://text2vec.org
  license: GPL-2
  summary: Fast and memory-friendly tools for text vectorization, topic modeling (LDA, LSA),
    word embeddings (GloVe), similarities. This package provides a source-agnostic streaming
    API, which allows researchers to perform analysis of collections of documents which
    are larger than available RAM. All core functions are parallelized to benefit from
    multicore machines.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH

# Package: text2vec
# Type: Package
# Version: 0.6
# Title: Modern Text Mining Framework for R
# License: GPL (>= 2) | file LICENSE
# Description: Fast and memory-friendly tools for text vectorization, topic modeling (LDA, LSA), word embeddings (GloVe), similarities. This package provides a source-agnostic streaming API, which allows researchers to perform analysis of collections of documents which are larger than available RAM. All core functions are parallelized to benefit from multicore machines.
# Authors@R: c( person("Dmitriy", "Selivanov", role = c("aut", "cre", "cph"), email = "selivanov.dmitriy@gmail.com"), person("Manuel", "Bickel", role = c("aut", "cph"), comment = "Coherence measures for topic models"), person("Qing", "Wang", role = c("aut", "cph"), comment = "Author of the WaprLDA C++ code"))
# Maintainer: Dmitriy Selivanov <selivanov.dmitriy@gmail.com>
# Encoding: UTF-8
# SystemRequirements: C++11
# Depends: R (>= 3.6.0), methods
# Imports: Matrix (>= 1.1), Rcpp (>= 1.0.3), R6 (>= 2.3.0), data.table(>= 1.9.6), rsparse (>= 0.3.3.4), stringi (>= 1.1.5), mlapi (>= 0.1.0), lgr (>= 0.2), digest (>= 0.6.8)
# LinkingTo: Rcpp, digest (>= 0.6.8)
# Suggests: magrittr, udpipe (>= 0.6), glmnet, testthat, covr, knitr, rmarkdown, proxy
# URL: http://text2vec.org
# BugReports: https://github.com/dselivanov/text2vec/issues
# VignetteBuilder: knitr
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2020-02-18 06:09:05 UTC; dselivanov
# Author: Dmitriy Selivanov [aut, cre, cph], Manuel Bickel [aut, cph] (Coherence measures for topic models), Qing Wang [aut, cph] (Author of the WaprLDA C++ code)
# Repository: CRAN
# Date/Publication: 2020-02-18 14:20:03 UTC
