appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mRvv7ipoCig8fkUXVCRmmTFvTKBUiDEbLZMnIRnos6yNxS5Twaq1VkhiZHUV7XoM36sMDzpb5A1wDbGey1eSDH0vjVxyMrnq/GagSIwUOmybt+jIKECt4rH4ZqD0rCYCH9wjwWJrcGgqkaIR1KopPeVTg4PQuwWU6B7Bk9XLIHNrQXLPrlNXWijueh741mwr262YeAe8GBOi4q0j6F3oeqx/qOJVb3AJiXBvN+7p/JqiejMCq3HLE24uY5tipZevSSCjIfh16swuIOB2e2qRR6O8bkZCcpRnwD+CplD3qO9LM92Az7F41zRimXbu8mDW0RPoa6IuogZPlfuZnaDydJlyJgbvmAFNYRgwQEgPtaumHwl5YC5LAfJOBCztz4d1nicQm7aWY1KYfFJc42xU+uEueDRK2p76tUnJ2ZqwsE8JVkoRnNcjKomSXvTnFyJZY6wkBScKPPKJ+qN8HYZo0PESl34QpLBdrHYow9Vllw27woTEgLprvHdph5oa9GDub1VyKcNs6ZL0eTkToaCV8yJfTaY6d5NpKpjKPhJgc/luc5jwrTd2EK66ZWRCwKIBO47DkjsFHNMehaszXf7cEAjuLEWr3YkLBL4oGSE2OwxCfdt1UliiTEwQIvN4QEQlcLBcH/MmAE3OdGEI9khkOP7xMYHKUweFFW0vLxChyrI=}
