travis:
  secure:
    BINSTAR_TOKEN: w2gTl3V/BdE4SraaH+0mMStLAepaAVRVfeUXRFP+EG85RYkiu10bhJtSab/a+cwdJjsN7RH7HT35MNKzcHM11ZBv8JDmNFjxB1er7MG+N8hXQIXWERZMd1QnEClLnUdRtdU74IcTUMQxakkQJ1TzXeOmWOABBNmCFniOkvRTyolur2JhrsQ/6jN1BQ5KowPHw/k5SoN5zFL3p2tmwjnAZH8Olb0mvmzFGMU9u+bR3xNA0cC0Elzc8C+53pNNTFk3t26cnM1IWQXQd7D+EikszR5r0LlVIBSJ1ThV60hYMl6YZ5o9SIuI1419GoZxLECxn/B8VS/PjB4DhgLx6/XGVnqPFsVS88zMfGJqXQtz2swRFZHazOOMIcxzvixr9gKdWkvgwyWBdNjUOB/M2PHx7hYap13RkdysSfu+dsB5P+jBg1pJkC6IkIr0JjeifdzhYIz7EG+TCADtCbYf275Ky26DBaxocDf0kwlirSvjdEJ6oGgFEiMeU59X+0Emw+lsNlUkL1v3dAkMHumHefXz06AjVkUQQ8O67Cx9xIEqO5fINicB/dyukkGjf7vcJDH0cjTit8mqC/MalY6XUS+gmO29gaIxmDGEAGAyW+3finusdD2Ee+I70AyHdaaSutk081Hymd8Wi5zuZy/E1mdBMupuLW2zmSuB5O4BC5EOA6I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
